name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build:
    name: Build distributions 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Fetch full git tags
      run: git fetch --tags

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install Python 3.13
      run: uv python install 3.13

    - name: Build
      run: uv build

    - name: Upload dist artifact
      uses: actions/upload-artifact@v7
      with:
        name: dist
        path: dist/


  publish-testpypi:
    name: Publish to TestPyPI
    needs: build
    if: github.event.release.prerelease == true
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment: testpypi

    steps:
    - name: Download dist
      uses: actions/download-artifact@v7
      with:
        name: dist
        path: dist/

    - name: Publish to TestPyPI 📦
      uses: pypa/gh-action-pypi-publish@v1.14.0
      with:
        repository-url: https://test.pypi.org/legacy/


  publish-pypi:
    name: Publish to PyPI
    needs: build
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment: pypi

    steps:
    - name: Download dist
      uses: actions/download-artifact@v7
      with:
        name: dist
        path: dist/

    - name: Publish to PyPI 📦
      uses: pypa/gh-action-pypi-publish@v1.14.0